version: 2

models:

  - name: stg_orders
    description: "Staged orders"
    tests:
      - cortex_revenue_dominance:
          customer_column: customer_key
          revenue_column: total_price
          threshold_percent: 50
          config:
            snowflake_warehouse: AI_XS_WH
    columns:
      - name: order_key
        tests:
          - not_null
          - unique
      - name: order_id
        tests:
          - cortex_key_duplication:
              columns: ['order_id']
              config:
                snowflake_warehouse: AI_XS_WH
      - name: status
        tests:
          - accepted_values:
              values: ['F', 'O', 'P']

  - name: stg_lineitem
    description: "Staged lineitems"
    tests:
      - cortex_key_duplication:
          columns: ['order_key', 'line_number']
          config:
            snowflake_warehouse: AI_XS_WH
    columns:
      - name: line_item_key
        tests:
          - not_null
          - unique
      - name: return_flag
        tests:
          - accepted_values:
              values: ['R', 'A', 'N']
      - name: status
        tests:
          - accepted_values:
              values: ['O', 'F']

  - name: stg_customers
    description: "Staged customers"
    columns:
      - name: customer_key
        tests:
          - not_null
          - unique

  - name: stg_part
    description: "Staged parts"
    columns:
      - name: part_key
        tests:
          - not_null
          - unique

  - name: stg_supplier
    description: "Staged suppliers"
    columns:
      - name: supplier_key
        tests:
          - not_null
          - unique

  - name: stg_partsupp
    description: "Staged part suppliers"
    columns:
      - name: part_supplier_key
        tests:
          - not_null
          - unique

  - name: stg_nation
    description: "Staged nations"
    columns:
      - name: nation_key
        tests:
          - not_null
          - unique

  - name: stg_region
    description: "Staged regions"
    columns:
      - name: region_key
        tests:
          - not_null
          - unique
  